import type { Diagnostic } from "../diagnostics/diagnostic.ts";

/**
 * Represents a file generated by the compiler.
 */
export interface GeneratedFile {
	/** Relative path from the output directory. */
	path: string;
	/** File content. */
	contents: string;
}

export interface GeneratedAsset {
	path: string;
	contents?: string | Uint8Array;
	sourceUrl?: string;
}

export interface SourcePlugin {
	name: string;
	run(input: SourcePluginInput): Promise<SourcePluginResult>;
}

export interface SourcePluginInput {
	cwd: string;
	args: Record<string, string | boolean>;
	config?: unknown;
}

export interface SourcePluginResult {
	html?: string;
	css?: string;
	assets?: GeneratedAsset[];
	files?: GeneratedFile[];
	diagnostics: Diagnostic[];
}

export interface TargetEmitResult {
	files: GeneratedFile[];
}

export interface TargetTestGenerateResult {
	files: GeneratedFile[];
}
